const data = [
  {phrase: 'Hello world!', options: ['English', 'German', 'Swedish'], answer: 'English'},
  {phrase: 'Përshendetje Botë!', options: ['Albanian', 'Russian', 'Greek'], answer: 'Albanian'},
  {phrase: 'Geiá sou Kósme!', options: ['Greek', 'French', 'Turkish'], answer: 'Greek'},
  {phrase: 'Kaixo Mundua!', options: ['Ukrainian', 'Spanish', 'Basque'], answer: 'Basque'},
  {phrase: 'Pozdrav svijete!', options: ['Finnish', 'Croatian', 'Georgian'], answer: 'Croatian'},
  {phrase: 'Ahoj světe!', options: ['Czech', 'Estonian', 'Swedish'], answer: 'Czech'},
  {phrase: 'Hej Verden!', options: ['Danish', 'German', 'Bengali'], answer: 'Danish'},
  {phrase: 'Ōhē biśba!', options: ['Igbo', 'Bengali', 'Malay'], answer: 'Bengali'},
  {phrase: '¡Hola Mundo!', options: ['Italian', 'Spanish', 'Turkish'], answer: 'Spanish'},
  {phrase: 'Tere, Maailm!', options: ['Indonesian', 'Norwegian', 'Estonian'], answer: 'Estonian'},
  {phrase: 'Zdraveĭ svyat!', options: ['Bulgarian', 'Nepali', 'Macedonian'], answer: 'Bulgarian'},
  {phrase: 'Privet, mir!', options: ['Danish', 'Urdu', 'Russian'], answer: 'Russian'},
  {phrase: 'Bonjour le monde!', options: ['Persian', 'French', 'Italian'], answer: 'French'},
  {phrase: 'Annyeong, segye!', options: ['Korean', 'Galician', 'Tsonga'], answer: 'Korean'},
  {phrase: 'Გamarjoba msoplio!', options: ['Hindi', 'Greek', 'Georgian'], answer: 'Georgian'},
  {phrase: 'Hallo Welt!', options: ['Czech', 'German', 'Dutch'], answer: 'German'},
  {phrase: 'Mwaramutse, isi!', options: ['Xhosa', 'Persian', 'Kinyarwanda'], answer: 'Kinyarwanda'},
  {phrase: 'Nyob zoo, ntiaj teb!', options: ['Russian', 'Hmong', 'Latvian'], answer: 'Hmong'},
  {phrase: 'Sveika pasaule!', options: ['Romanian', 'Finnish', 'Latvian'], answer: 'Latvian'},
  {phrase: 'Helló Világ!', options: ['Slovenian', 'Dutch', 'Hungarian'], answer: 'Hungarian'},
  {phrase: 'Ndewo Ụwa!', options: ['Igbo', 'Slovak', 'Thai'], answer: 'Igbo'},
  {phrase: 'Halo Dunia!', options: ['Chichiwa', 'Spanish', 'Indonesian'], answer: 'Indonesian'},
  {phrase: 'Dia duit, domhan!', options: ['Vietnamese', 'Irish', 'Catalan'], answer: 'Irish'},
  {phrase: 'Ciao mondo!', options: ['Italian', 'Macedonian', 'French'], answer: 'Italian'},
  {phrase: 'Kon\'nichiwa sekai!', options: ['Chinese', 'Japanese', 'Malay'], answer: 'Japanese'},
  {phrase: 'Pozdravljen, svet!', options: ['Slovenian', 'Czech', 'Latvian'], answer: 'Slovenian'},
  {phrase: 'Sain uu, delkhii!', options: ['Hindi', 'Mongolian', 'Icelandic'], answer: 'Mongolian'},
  {phrase: 'Hei maailma!', options: ['Finnish', 'Yiddish', 'Sanskrit'], answer: 'Finnish'},
  {phrase: 'Aloha, honua!', options: ['Filipino', 'Hawaiian', 'Mongolian'], answer: 'Hawaiian'},
  {phrase: 'Witaj świecie!', options: ['Polish', 'Albanian', 'Uzbek'], answer: 'Polish'},
  {phrase: 'Salut Lume!', options: ['Italian', 'Romanian', 'Spanish'], answer: 'Romanian'},
  {phrase: 'Talofa, lalolagi!', options: ['Maori', 'Samoan', 'Malay'], answer: 'Samoan'},
  {phrase: 'Lefatše Lumela!', options: ['Norwegian', 'Ukrainian', 'Sesotho'], answer: 'Sesotho'},
  {phrase: 'Kia ora, te ao!', options: ['Hawaiian', 'Maori', 'Xhosa'], answer: 'Maori'},
  {phrase: 'Salamu, Dunia!', options: ['Hindi', 'Swahili', 'Arabic'], answer: 'Swahili'},
  {phrase: 'Hej världen!', options: ['Swedish', 'Finnish', 'Welsh'], answer: 'Swedish'},
  {phrase: 'S̄wạs̄dī chāw lok!', options: ['Sanskrit', 'Thai', 'Maori'], answer: 'Thai'},
  {phrase: 'Xewani, misava!', options: ['Thai', 'Assamese', 'Tsonga'], answer: 'Tsonga'},
  {phrase: 'Selam Dünya!', options: ['Turkish', 'Swahili', 'Norwegian'], answer: 'Turkish'},
  {phrase: 'Chào thế giới!', options: ['Italian', 'Persian', 'Vietnamese'], answer: 'Vietnamese'},
  {phrase: 'Helo Byd!', options: ['Welsh', 'Swedish', 'Serbian'], answer: 'Welsh'},
  {phrase: 'Molo Lizwe!', options: ['Macedonian', 'Xhosa', 'Turkish'], answer: 'Xhosa'},
  {phrase: 'Hela velt!', options: ['Swedish', 'Yiddish', 'Welsh'], answer: 'Yiddish'},
  {phrase: 'Mo ki O Ile Aiye!', options: ['Yoruba', 'Hawaiian', 'Maltese'], answer: 'Yoruba'},
  {phrase: 'Sawubona Mhlaba!', options: ['Arabic', 'Portugese', 'Zulu'], answer: 'Zulu'},
  {phrase: 'Yá\'áá\'ééh t\'áá ałtsoní', options: ['Navajo', 'Maori', 'Thai'], answer: 'Navajo'},
]